### ISSUE TITLE
get rid of the lookup_flowproperty hack

### ISSUE THREAD

**Issue by mfastudillo** [mfastudillo/brightway2-io#13]
in the hackathon we used the [lookup_flowproperty ](https://github.com/mfastudillo/brightway2-io/blob/14a8d11d46e73fa3c07576b6a811def514b710d2/bw2io/extractors/ilcd.py#L230)function to add the unit and (flow property?) to exchanges. Sometimes there are uuids that are not in the dictionary.

we should get rid of this hack and extract it from the ilcd file... but I don't know where this info is.

**Comment by mfastudillo** [comment]
example of "flow properties?" that seems to be missing `Goods transport` ,  `Energy`

**Comment by cswh** [comment]
Something like this should work to get the unit and flow property name from the ILCD files itself:

```python
import xmltodict
path = "path/to/ILCD"

def lookup_flowproperty(flowproperty_uuid:str):
    with open(os.path.join(ilcd_path, "flowproperties", flowproperty_uuid+".xml"), 'r') as file:
        xml_dict_fp = xmltodict.parse(file.read())

    flow_property_name = xml_dict_fp['flowPropertyDataSet']['flowPropertiesInformation']['dataSetInformation']['common:name']['#text']
    unit_uuid = xml_dict_fp['flowPropertyDataSet']['flowPropertiesInformation']["quantitativeReference"]["referenceToReferenceUnitGroup"]["@refObjectId"]

    with open(os.path.join(ilcd_path, "unitgroupus", unit_uuid+".xml"), 'r') as file:
        xml_dict_ug = xmltodict.parse(file.read())

    ref_unit_id = xml_dict_ug['unitGroupDataSet']['unitGroupInformation']["quantitativeReference"]["referenceToReferenceUnit"]

    try:
        units = {u["@dataSetInternalID"]: {"name": u["name"], "meanValue": u["meanValue"]} for u in xml_dict_ug["unitGroupDataSet"]["units"]["unit"]}
    except:
        units = {u["@dataSetInternalID"]: {"name": u["name"], "meanValue": u["meanValue"]} for u in [xml_dict_ug["unitGroupDataSet"]["units"]["unit"]]}

    unit_name = units[ref_unit_id]["name"]

    return (unit_name, flow_property_name)
```

**Comment by cswh** [comment]
But probably it would be best to read all flows, flow properties and unit groups at once. I can write some code for that in the next days...

**Comment by mfastudillo** [comment]
I've just updated the main branch with some changes to be able to parse flow properties. I think the way would be to extend the list of xpaths in the [xpaths function](https://github.com/mfastudillo/brightway2-io/blob/14a8d11d46e73fa3c07576b6a811def514b710d2/bw2io/extractors/ilcd.py#L230 ) 

so to test if a path results in something useful you can run something like
```python
from bw2io.extractors import ilcd
path_to_GLAD_example = Path('bw2io/data/examples/ilcd_example.zip')
etree_dict = ilcd.extract_zip(path_to_GLAD_example)

p = {'whatever':'/flowPropertyDataSet/flowPropertiesInformation/dataSetInformation/common:name/text()'}

for _,etree in etree_dict.get('flowproperties').items():
    print(ilcd.apply_xpaths_to_xml_file(p,etree))

```

if it does it can be added to a dictionary in the xpaths function in the extractor. Then we'd need to slightly modify `extract_all_relevant_info` (https://github.com/mfastudillo/brightway2-io/blob/14a8d11d46e73fa3c07576b6a811def514b710d2/bw2io/extractors/ilcd.py#L136)

**Comment by mfastudillo** [comment]
I've started a branch `flowproperties` where I've already done a few of these things.

it has a dict in xpaths function where to add new paths of info from flow properties that needs to be extracted. These will appear in the object used to create the database

```python
path_to_GLAD_example = Path('bw2io/data/examples/ilcd_example.zip')
data = ilcd.extract(path_to_GLAD_example)
data[0]['flow properties'] # there is only one activity in that ilcd file
```

**Comment by cswh** [comment]
Ok @mfastudillo  Do you still need support for this issue?

**Comment by mfastudillo** [comment]
@cswh I'd need some help to finish this, but perhaps with the code that you wrote I can finish it up myself. There are other issues if you want to pick one

**Comment by mfastudillo** [comment]
solved with the latests commits
