### ISSUE TITLE
datasets in ilcd format from lcacommons fails to import

### ISSUE THREAD

**Issue by mfastudillo** [mfastudillo/brightway2-io#6]
there are many datasets available, but unlike datasets picked from GLAD the current import fails

https://www.lcacommons.gov/lca-collaboration/

among the reasons may be that there is more than one exchange of the type "product flow", while the current importer assumes there is one.

**Comment by mfastudillo** [comment]
ok, it seems I need to use the `FEDEFLv1.0.3-ecoinventEFv3.7.xlsx` as a mapping file for datasets from the lcacommons

**Comment by WesIngwersen** [comment]
@mfastudillo depending on the repository you are using on the LCA commons, some use FEDEFL and some do not.
The EPA managed repos all use the FEDEFL

We haven't looked at the ILCD exports in particular so I can't confirm that the flows are as is. Happy to check this out if you provide one or more examples

**Comment by mfastudillo** [comment]
Thanks Wes, 

Here is an example. Using the FEDEFL mapping the linking kind of works. Maybe part of the problem is that the biosphere database in this version links to ecoinvent 3.9, not 3.7 .. 

https://github.com/mfastudillo/brightway2-io/blob/master/example.ipynb

**Comment by mfastudillo** [comment]
the import now works, although the mapping of flows is still incomplete
